#=============================================================================
# basic.toml --- basic configuration example for SpaceVim
# Copyright (c) 2016-2020 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

[[custom_plugins]]
repo = 'altercation/vim-colors-solarized'
merged = 0

# [[custom_plugins]]
# repo = 'wsdjeg/vim-todo'
# merged = 0

[[custom_plugins]]
# requires `npm -g instant-markdown-d`
repo = 'instant-markdown/vim-instant-markdown'
merged = 0

[[custom_plugins]]
repo = 'vim-scripts/dbext.vim'
merged = 0

# [[custom_plugins]]
# repo = 'vlime/vlime'
# merged = 0

# [[custom_plugins]]
# repo = 'preservim/nerdtree'
# merged = 0

[options]
bootstrap_before = "spacevim#before"
 colorscheme = "solarized" #"gruvbox"
 colorscheme_bg = "dark"
# colorscheme_bg = "light"
enable_guicolors = false
enable_statusline_mode = true
enable_tabline_filetype_icon = false
enable_os_fileformat_icon = false
statusline_unicode_symbols = false
statusline_separator = "nil"
statusline_iseparator = "nil"
buffer_index_type = 0 #4
windows_index_type = 3
vimcompatible = true
filemanager = "nerdtree"
enable_vimfiler_welcome = true
guifont = "Courier Prime Sans:h14"
#   "Rec Mono Linear:h14"
# "IBM Plex Mono:h13"
# "Monaco:h12"
# "Spot Mono:h15"
# "Anka/Coder:h13"
# "DecimaMonoX:h14"
# "Inconsolata:h14"
# "ProggyVector:h14"
# "Space Mono:h14"
# "Atkinson Hypermono:h13"
automatic_update = true

# Enable autocomplete layer
[[layers]]
name = 'autocomplete'
auto_completion_return_key_behavior = "complete"
auto_completion_tab_key_behavior = "cycle"
auto_completion_delay = 200

[[layers]]
name = 'shell'
default_position = 'top'
default_height = 30

[[layers]]
name = "tmux"

#[[layers]]
#name=colorscheme

[[layers]]
name = "lang#python"
python_interpreter = "/usr/local/bin/python3"

[[layers]]
name = "lang#javascript"

[[layers]]
name = "lang#racket"

[[layers]]
name = "lang#scheme"

[[layers]]
name = "lang#ruby"

[[layers]]
name = "lang#r"

[[layers]]
name = "lang#json"

[[layers]]
name = "lang#markdown"

# [[layers]]
# name = "lang#scala"

[[layers]]
name = "VersionControl"

[[layers]]
name = "lang#perl"
